In [4]:
import numpy as np
import pandas as pd

In [5]:
duomenys = pd.read_csv('example.csv')

In [3]:
duomenys.head()

   Numeris               Seniūnija     Plotas  Gyventojų skaičius
0        1        Verkių seniūnija  55,65 km²               49359
1        2    Antakalnio seniūnija   77,2 km²               39758
2        3    Pašilaičių seniūnija    8,2 km²               39543
3        4  Fabijoniškių seniūnija    4,1 km²               38253
4        5      Pilaitės seniūnija   13,8 km²               26376

In [4]:
duomenys.to_csv('result.csv', index=False)

In [8]:
duomenys_xls = pd.read_excel('example.xls', sheet_name='example')

In [9]:
duomenys_xls.head()

   Numeris               Seniūnija     Plotas  Gyventojų skaičius
0        1        Verkių seniūnija  55,65 km²               49359
1        2    Antakalnio seniūnija   77,2 km²               39758
2        3    Pašilaičių seniūnija    8,2 km²               39543
3        4  Fabijoniškių seniūnija    4,1 km²               38253
4        5      Pilaitės seniūnija   13,8 km²               26376

In [12]:

duomenys_xls.to_excel('result_test.xls', sheet_name = 'Sheet1')

C:\Users\Valdemaras\AppData\Local\Temp\ipykernel_22636\1919151626.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  duomenys_xls.to_excel('result_test.xls', sheet_name = 'Sheet1')

ModuleNotFoundError: No module named 'xlwt'

In [19]:
duomenys_html = pd.read_html('https://lt.wikipedia.org/wiki/Vilniaus_miesto_savivaldyb%C4%97')

In [13]:
duomenys_html

[   Vilniaus miesto savivaldybė Vilniaus miesto savivaldybė.1
 0                          NaN                           NaN
 1                          NaN                           NaN
 2                          NaN                           NaN
 3                          NaN                           NaN
 4                          NaN                           NaN
 5                          NaN                           NaN
 6                     Valstybė                       Lietuva
 7                    Apskritis            Vilniaus apskritis
 8      Administracinis centras                       Vilnius
 9           Seniūnijų skaičius                            21
 10                Įkūrimo data                       1995 m.
 11                       Meras    Remigijus Šimašius (2019–)
 12                         NaN                           NaN
 13                   Gyventojų                    556 490[1]
 14                      Plotas                       401 km²
 15                    Tankumas                 1 388 žm./km²
 16           Aukščiausia vieta   230,7 m (Rokantiškių kalva)
 17                         NaN                           NaN
 18                 Tinklalapis                    vilnius.lt
 19                    Vikiteka   Vilniaus miesto savivaldybė,
                                                     0  \
 0   Ž • A • RVilniaus miesto savivaldybės saugomos...
 1   Ž • A • RVilniaus miesto savivaldybės saugomos...
 2                                                 NaN
 3                             Valstybiniai rezervatai
 4                                                 NaN
 5                                  Regioniniai parkai
 6                                                 NaN
 7                            Valstybiniai draustiniai
 8                                                 NaN
 9                            Savivaldybės draustiniai
 10                                                NaN
 11                                   Gamtos paminklai
 12                                                NaN
 13               Valstybiniai gamtos paveldo objektai
 14                                                NaN
 15               Savivaldybės gamtos paveldo objektai

                                                     1
 0                                                 NaN
 1   Ž • A • RVilniaus miesto savivaldybės saugomos...
 2                                                 NaN
 3                Vilniaus pilių kultūrinis rezervatas
 4                                                 NaN
 5   Pavilnių regioninis parkas • Verkių regioninis...
 6                                                 NaN
 7   Dvarčionių geomorfologinis • Griovių geomorfol...
 8                                                 NaN
 9   Aukštagirio geomorfologinis • Cedrono aukštupi...
 10                                                NaN
 11  Plikakalnio atodanga • Pūčkorių atodanga • Šeš...
 12                                                NaN
 13              Aukštųjų Panerių geležinkelio tunelis
 14                                                NaN
 15  Antakalnio parko kedrinė pušis • Aštuonių klev...  ,
    Ž • A • RVilniaus miesto savivaldybės saugomos teritorijos  \
 0                                                 NaN
 1                             Valstybiniai rezervatai
 2                                                 NaN
 3                                  Regioniniai parkai
 4                                                 NaN
 5                            Valstybiniai draustiniai
 6                                                 NaN
 7                            Savivaldybės draustiniai
 8                                                 NaN
 9                                    Gamtos paminklai
 10                                                NaN
 11               Valstybiniai gamtos paveldo objektai
 12                                                NaN
 13               Savivaldybės gamtos paveldo objektai

    Ž • A • RVilniaus miesto savivaldybės saugomos teritorijos.1
 0                                                 NaN
 1                Vilniaus pilių kultūrinis rezervatas
 2                                                 NaN
 3   Pavilnių regioninis parkas • Verkių regioninis...
 4                                                 NaN
 5   Dvarčionių geomorfologinis • Griovių geomorfol...
 6                                                 NaN
 7   Aukštagirio geomorfologinis • Cedrono aukštupi...
 8                                                 NaN
 9   Plikakalnio atodanga • Pūčkorių atodanga • Šeš...
 10                                                NaN
 11              Aukštųjų Panerių geležinkelio tunelis
 12                                                NaN
 13  Antakalnio parko kedrinė pušis • Aštuonių klev...            ,
              0                 1            2
 0          NaN       54° 49′ 20″          NaN
 1  25° 01′ 40″  Vilniaus miestas  25° 28′ 50″
 2          NaN               NaN          NaN
 3          NaN  Vilniaus miestas          NaN
 4          NaN               NaN          NaN
 5          NaN       54° 34′ 00″          NaN,
     0                 1   2
 0 NaN               NaN NaN
 1 NaN  Vilniaus miestas NaN
 2 NaN               NaN NaN,
                              0  \
 0                          NaN
 1  2001 m. gyventojų surašymas
 2          2009 m. gyvenvietės
 3  2011 m. gyventojų surašymas
 4          2016 m. gyvenvietės
 5         2020 m. suskirstymas
 6  2021 m. gyventojų surašymas

                                                  1
 0  Vilniaus miesto savivaldybės istoriniai sąrašai
 1                      2001 m. gyventojų surašymas
 2                              2009 m. gyvenvietės
 3                      2011 m. gyventojų surašymas
 4                              2016 m. gyvenvietės
 5                             2020 m. suskirstymas
 6                      2021 m. gyventojų surašymas  ,
    Savivaldybės istorija                            \
                    Metai Plotas, km² Gyventojų sk.
 0                1942 m.         NaN       146 300
 1                1949 m.       139.0           NaN
 2                1957 m.         NaN           NaN
 3                1959 m.       142.0       230 769
 4                1967 m.       153.0       316 400
 5                1970 m.       265.0       372 100
 6                1972 m.       262.0           NaN
 7                1976 m.       263.0       445 900
 8                1979 m.         NaN       475 825
 9                1988 m.       287.0       577 000
 10               1989 m.       287.0       576 747
 11               1999 m.       401.0       588 400
 12    2001 m. (Išsamiau)       401.0       553 904

                                             \
                               Suskirstymas
 0                                      NaN
 1   5 miesto rajonai (11 miesto apylinkių)
 2                         4 miesto rajonai
 3                         4 miesto rajonai
 4                                      NaN
 5                         4 miesto rajonai
 6                         4 miesto rajonai
 7                                      NaN
 8                         4 miesto rajonai
 9                         4 miesto rajonai
 10                                     NaN
 11                                     NaN
 12                            21 seniūnija


                                  Gyvenvietės
 0                                        NaN
 1                                        NaN
 2                                        NaN
 3                        1 miestas (Vilnius)
 4                                        NaN
 5                                  1 miestas
 6                                  1 miestas
 7                                  1 miestas
 8                                  1 miestas
 9                                  1 miestas
 10                                 1 miestas
 11                                       NaN
 12  2 miestai (Grigiškės, Vilnius), 3 kaimai  ,
                                            0  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                1959 m.sur.
 2                                    230 769
 3                                    2019 m.
 4                                    552 131
 5             Demografinės raidos histograma
 6             Demografinės raidos histograma
 7                                        NaN

                                            1  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                1970 m.sur.
 2                                    372 100
 3                             2021 m.sur.[2]
 4                                    556 490
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN

                                            2  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                1979 m.sur.
 2                                    475 825
 3                                          -
 4                                          -
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN

                                            3  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                1989 m.sur.
 2                                    576 747
 3                                          -
 4                                          -
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN

                                            4  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                2001 m.sur.
 2                                    553 904
 3                                          -
 4                                          -
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN

                                            5  \
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                    2005 m.
 2                                    560 190
 3                                          -
 4                                          -
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN

                                            6
 0  Demografinė raida tarp 1959 m. ir 2021 m.
 1                                2011 m.sur.
 2                                    538 968
 3                                          -
 4                                          -
 5             Demografinės raidos histograma
 6                                        NaN
 7                                        NaN  ,
 Empty DataFrame
 Columns: [Demografinės raidos histograma]
 Index: [],
                        Seniūnija     Plotas  Gyventojai (2020 m.) [3]
 0           Antakalnio seniūnija   77,2 km²                     40637
 1         Fabijoniškių seniūnija    4,1 km²                     38237
 2            Grigiškių seniūnija    7,1 km²                     11466
 3          Justiniškių seniūnija   2,98 km²                     26818
 4         Karoliniškių seniūnija    4,0 km²                     25532
 5              Lazdynų seniūnija   10,3 km²                     32325
 6         Naujamiesčio seniūnija    4,8 km²                     32280
 7           Naujininkų seniūnija   41,1 km²                     31568
 8    Naujosios Vilnios seniūnija   39,3 km²                     38571
 9              Panerių seniūnija  84,94 km²                     10367
 10          Pašilaičių seniūnija    8,2 km²                     40823
 11            Pilaitės seniūnija   13,8 km²                     27725
 12                Rasų seniūnija   12,7 km²                     11592
 13         Senamiesčio seniūnija    4,5 km²                     22000
 14            Šeškinės seniūnija    4,4 km²                     29885
 15           Šnipiškių seniūnija   3,12 km²                     15603
 16              Verkių seniūnija  55,65 km²                     50688
 17           Vilkpėdės seniūnija   10,3 km²                     19720
 18         Viršuliškių seniūnija    2,5 km²                     14153
 19             Žirmūnų seniūnija    8,5 km²                     44079
 20             Žvėryno seniūnija    2,7 km²                     13620
 21  Nedeklaravę gyvenamos vietos        NaN                      8936,
                                                    0  \
 0  Almata, Kazachija  Astana, Kazachija  Briuseli...

                                                    1  \
 0  Erfurtas, Vokietija  Gdanskas, Lenkija  Guangd...

                                                    2  \
 0  Madisonas, JAV  Minskas, Baltarusija  Olborgas...

                                                    3
 0  Stokholmas, Švedija  Strasbūras, Prancūzija  T...  ,
                               Unnamed: 0  \
 0                                    NaN
 1                                   2018
 2            Bendros valstybės paslaugos
 3                                 Gynyba
 4   Viešoji tvarka ir visuomenės apsauga
 5                              Ekonomika
 6                       Aplinkos apsauga
 7             Būstas ir komunalinis ūkis
 8                      Sveikatos apsauga
 9           Poilsis, kultūra ir religija
 10                             Švietimas
 11                     Socialinė apsauga
 12   Finansinio turto įsigijimo išlaidos
 13                              Iš viso:

    Savivaldybių biudžetų išlaidos tūkst. EUR[5]  \
 0                                           NaN
 1                                          2019
 2                                      68 863,6
 3                                          2121
 4                                       2 291,5
 5                                      42 232,1
 6                                      37 201,0
 7                                      74 410,2
 8                                      10 332,8
 9                                      22 314,5
 10                                    287 404,2
 11                                     63 697,6
 12                                           00
 13                                    608 959,6

    Savivaldybių biudžetų išlaidos tūkst. EUR[5].1
 0                                             NaN
 1                                             NaN
 2                                        52 206,7
 3                                            1688
 4                                         2 719,1
 5                                        58 094,6
 6                                        42 331,2
 7                                        77 406,8
 8                                        15 268,8
 9                                        22 904,7
 10                                      324 714,5
 11                                       64 796,4
 12                                           5901
 13                                      661 201,7  ,
                                            Unnamed: 0  \
 0                                                 NaN
 1                                                2018
 2                                           Mokesčiai
 3                           Gyventojų pajamų mokestis
 4                                     Turto mokesčiai
 5                        Prekių ir paslaugų mokesčiai
 6                                           Dotacijos
 7                Lėšos pagal tarpusavio atsiskaitymus
 8                                       Kitos pajamos
 9   Sandoriai dėl materialiojo ir nematerialiojo t...
 10                                       Viso pajamų:

    Savivaldybių biudžetų pajamos tūkst. EUR[6]  \
 0                                          NaN
 1                                         2019
 2                                    337 133,5
 3                                    295 265,4
 4                                     40 527,3
 5                                      1 340,8
 6                                    202 933,3
 7                                            −
 8                                     56 652,6
 9                                      7 075,9
 10                                   603 795,3

    Savivaldybių biudžetų pajamos tūkst. EUR[6].1
 0                                            NaN
 1                                            NaN
 2                                      358 667,0
 3                                      314 283,1
 4                                        2 719,1
 5                                        1 348,4
 6                                      221 896,0
 7                                              −
 8                                       69 536,4
 9                                       10 213,8
 10                                     660 313,2  ,
                                                     0  \
 0   Ž • A • RLietuvos administracinis suskirstymas...
 1   Ž • A • RLietuvos administracinis suskirstymas...
 2                                                 NaN
 3                                   Alytaus apskritis
 4                                                 NaN
 5                                     Kauno apskritis
 6                                                 NaN
 7                                 Klaipėdos apskritis
 8                                                 NaN
 9                              Marijampolės apskritis
 10                                                NaN
 11                                Panevėžio apskritis
 12                                                NaN
 13                                  Šiaulių apskritis
 14                                                NaN
 15                                 Tauragės apskritis
 16                                                NaN
 17                                   Telšių apskritis
 18                                                NaN
 19                                   Utenos apskritis
 20                                                NaN
 21                                 Vilniaus apskritis

                                                     1  \
 0                                                 NaN
 1   Ž • A • RLietuvos administracinis suskirstymas...
 2                                                 NaN
 3   · Alytaus miesto savivaldybė · Alytaus rajono ...
 4                                                 NaN
 5   · Birštono savivaldybė · Jonavos rajono saviva...
 6                                                 NaN
 7   · Klaipėdos miesto savivaldybė · Klaipėdos raj...
 8                                                 NaN
 9   · Kalvarijos savivaldybė · Kazlų Rūdos savival...
 10                                                NaN
 11  · Biržų rajono savivaldybė · Kupiškio rajono s...
 12                                                NaN
 13  · Akmenės rajono savivaldybė · Joniškio rajono...
 14                                                NaN
 15  · Jurbarko rajono savivaldybė · Pagėgių saviva...
 16                                                NaN
 17  · Mažeikių rajono savivaldybė · Plungės rajono...
 18                                                NaN
 19  · Anykščių rajono savivaldybė · Ignalinos rajo...
 20                                                NaN
 21  · Elektrėnų savivaldybė · Šalčininkų rajono sa...

                                                     2
 0                                                 NaN
 1   Ž • A • RLietuvos administracinis suskirstymas...
 2                                                 NaN
 3                                                 NaN

In [14]:
duomenys_html[6].head()

  Savivaldybės istorija                            \
                  Metai Plotas, km² Gyventojų sk.
0               1942 m.         NaN       146 300
1               1949 m.       139.0           NaN
2               1957 m.         NaN           NaN
3               1959 m.       142.0       230 769
4               1967 m.       153.0       316 400


                             Suskirstymas          Gyvenvietės
0                                     NaN                  NaN
1  5 miesto rajonai (11 miesto apylinkių)                  NaN
2                        4 miesto rajonai                  NaN
3                        4 miesto rajonai  1 miestas (Vilnius)
4                                     NaN                  NaN

In [15]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///duomenys.db')

In [16]:
duomenys_html[6].to_sql('savivaldos', con=engine, index=False)

ValueError: Table 'savivaldos' already exists.

In [17]:
duomenys_sql = pd.read_sql('savivaldos', con=engine)

In [18]:
duomenys_sql

    Numeris                    Seniūnija     Plotas  Gyventojų skaičius
0         1             Verkių seniūnija  55,65 km²               49359
1         2         Antakalnio seniūnija   77,2 km²               39758
2         3         Pašilaičių seniūnija    8,2 km²               39543
3         4       Fabijoniškių seniūnija    4,1 km²               38253
4         5           Pilaitės seniūnija   13,8 km²               26376
5         6        Justiniškių seniūnija   2,98 km²               26818
6         7        Viršuliškių seniūnija    2,5 km²               14177
7         8           Šeškinės seniūnija    4,4 km²               34084
8         9          Šnipiškių seniūnija   3,12 km²               16657
9        10            Žirmūnų seniūnija    8,5 km²               44028
10       11       Karoliniškių seniūnija    4,0 km²               25770
11       12            Žvėryno seniūnija    2,7 km²               13465
12       13          Grigiškių seniūnija    7,1 km²               11592
13       14            Lazdynų seniūnija   10,3 km²               31900
14       15          Vilkpėdės seniūnija   10,3 km²               20472
15       16       Naujamiesčio seniūnija    4,8 km²               30693
16       17        Senamiesčio seniūnija    4,5 km²               21503
17       18  Naujosios Vilnios seniūnija   39,3 km²               37372
18       19            Panerių seniūnija  84,94 km²               10064
19       20         Naujininkų seniūnija   41,1 km²               31407
20       21               Rasų seniūnija   12,7 km²               11463